image: node:12.18.3

cache:
  untracked: true
  paths:
    - node_modules/

before_script:
  - npm ci --cache

stages:
  - ci
  - deploy

ci:lint:
  stage: ci
  script:
    - npm run lint

ci:test:
  stage: ci
  script:
    - npm run test

ci:coverage-above-90:
  stage: ci
  script:
    - npm run test:coverage-above-90

deploy:
  stage: deploy
  script:
    # Trigger to run build and deploy on netlify
    - curl -X POST -d {} $URL_STAGING
  only:
    - develop
