image: node:12.18.3

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  - test-lint
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm install
  only:
    - develop
    - master

test:
  stage: test-lint
  script:
    - npm run test
    - npm run lint
  only:
    - develop
    - master

build:
  stage: build
  script:
    - npm run build-storybook
  artifacts:
    paths:
      - storybook-static
  only:
    - master
    - develop

deploy:
  stage: deploy
  script:
    - curl -X POST -d {} $URL_STAGING
  dependencies:
    - build
  only:
    - develop
