image: node:12.18.3

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  - test
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm install
  only:
    - feature/DRC-51

test:
  stage: test
  script:
    - npm run test
  only:
    - feature/DRC-51

build:
  stage: build
  script:
    - npm run build-storybook
  artifacts:
    paths:
      - storybook-static
  only:
    - feature/DRC-51

deploy:
  stage: deploy
  script:
    - curl -X POST -d {} https://api.netlify.com/build_hooks/5f518dbf2315600154ad1972
  dependencies:
    - build
  only:
    - feature/DRC-51
